refactor: 백그라운드에서 실행

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,7 +29,7 @@ jobs:
           echo DB_URL=${{ secrets.DB_URL }} >> .env
           echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
           echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
-          
+
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -73,7 +73,7 @@ jobs:
                 -e JWT_SECRET_KEY='\''${{ secrets.JWT_SECRET_KEY }}'\'' \
                 ${{ env.DOCKER_IMAGE }}",
               "sleep 5",
-              "if docker ps -d | grep -q app; then echo \"Deployment successful\"; else echo \"Deployment failed\" && exit 1; fi",
+              "if docker ps | grep -q app; then echo \"Deployment successful\"; else echo \"Deployment failed\" && exit 1; fi",
               "echo \"Deployment completed at $(date)\""
             ]' \
             --timeout-seconds 600 \
